# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e6245c7bd19170c79266a352da3ce3a891066407070163791063b6fd36bb0255f9027e22fb8eabc6cc090a15714271db4b2ff7bea4d9518d651dfb8d3d85f6d

test:
  secret_key_base: 1fef63276eba5d23b906a71a23d0c70cc6820042b87aba84fa1a370983bca66fee26ae35dd4005befc63d1b8c075af9f93ca12fac6c7457dd3dd282ca920f286

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
